# -*- coding: utf-8 -*-
"""Copia de Copia de Código Trabajo Final

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWBfcqApV7xZ1kdVqurZTk4R-TkLbvrC
"""

#Lee la base de datos
import pandas as pd
df_top500 = pd.read_csv("/content/top500.csv")

# To install Plotly for deployment environments like Streamlit, add 'plotly' to a 'requirements.txt' file.
!pip install plotly

#Importa estadisticas y tablas SQL
import plotly.express as px

#Define el número de películas por país y los pone en columnas
country_count = df_top500["country"].value_counts().reset_index()
country_count.columns = ["country", "Cantidad de películas"]

#Ilustra el mapa
fig = px.choropleth(
    country_count,
#Define las variables para mostrarse
    locations="country",
    locationmode="country names",
    color="Cantidad de películas",
#Crea la barra de películas
    hover_name="country",
    hover_data=["Cantidad de películas"],
    color_continuous_scale="Greens",
#Titulo del mapa
    title="Cantidad de películas del Top 500 por país"
)
#Da tamaño al mapa.
fig.update_layout(
    width=1000,
    height=600
)

fig.show()

#Importa archivos para mostrarlos
from IPython.display import HTML, display

#Equivale el resultado al dataframe que almacena los países de las películas
country = input("Escribe el nombre del país para ver sus películas: ")

#Equivale el resultado al dataframe que almacena los países de las películas
resultado = df_top500[df_top500["country"] == country]

#Visualiza todas las películas con imágenes
if resultado.empty:
#Formateo el texto
    print(f"No se encontraron películas para {country} en el Top 500.")
else:
    print(f"Películas de {country} (Top 500):\n")
    for index, row in resultado.sort_values(by='averageRating', ascending=False).iterrows():
        title = row["title"]
        year = row["year"]
        director = row["director/0"] if "director/0" in row and pd.notna(row["director/0"]) else "N/A"
        avg_rating = row["averageRating"]
        poster_url = row["posterUrl"] if "posterUrl" in row and pd.notna(row["posterUrl"]) else ""

#Coloca las imágenes
        movie_info_html = f""
        if poster_url:
            movie_info_html += f"<div style='display:flex; align-items:center; margin-bottom: 20px;'>"
            movie_info_html += f"<img src='{poster_url}' style='width:100px; height:auto; margin-right:15px;'>"
            movie_info_html += f"<div>"
        else:
            movie_info_html += f"<div>"

        movie_info_html += f"  <strong>Título:</strong> {title}<br>"
        movie_info_html += f"  <strong>Año:</strong> {year}<br>"
        movie_info_html += f"  <strong>Director:</strong> {director}<br>"
        movie_info_html += f"  <strong>Calificación Promedio (Ranking):</strong> {avg_rating}<br>"
        movie_info_html += f"</div>"

        if poster_url:
            movie_info_html += f"</div>"

        display(HTML(movie_info_html))
        print("-----------------------------------------")

#Importa archivos para mostrarlos
import pandas as pd
from IPython.display import HTML, display

#Equivale el resultado al dataframe que almacena los países de las géneros
genre_cols = [col for col in df_top500.columns if 'genres/' in col]
df_top500['genres_combined'] = df_top500[genre_cols].apply(lambda row: ', '.join(row.dropna().astype(str)), axis=1)

#Coloca el género
print("Géneros admitidos: Adventure, Drama, Fantasy, Music, Romance, Thriller, War, Western")
genre_input = input("Escribe el nombre del género para ver sus películas: ")

#Determina si el input está en la lista hecha de generos
resultado_genero = df_top500[df_top500['genres_combined'].str.contains(genre_input, case=False, na=False)]

#Visualiza todas las películas con imágenes
if resultado_genero.empty:
#Formateo el texto
    print(f"No se encontraron películas para el género '{genre_input}' en el Top 500.")
else:
    print(f"Películas del género '{genre_input}' (Top 500):\n")
    for index, row in resultado_genero.sort_values(by='averageRating', ascending=False).head(10).iterrows():
        title = row["title"]
        year = row["year"]
        director = row["director/0"] if "director/0" in row and pd.notna(row["director/0"]) else "N/A"
        avg_rating = row["averageRating"]
        poster_url = row["posterUrl"] if "posterUrl" in row and pd.notna(row["posterUrl"]) else ""

#Se visualizan las imágenes
        movie_info_html = ""
        if poster_url:
            movie_info_html += f"<div style='display:flex; align-items:center; margin-bottom: 20px;'>"
            movie_info_html += f"<img src='{poster_url}' style='width:100px; height:auto; margin-right:15px;'>"
            movie_info_html += f"<div>"
        else:
            movie_info_html += f"<div>"

        movie_info_html += f"  <strong>Título:</strong> {title}<br>"
        movie_info_html += f"  <strong>Año:</strong> {year}<br>"
        movie_info_html += f"  <strong>Director:</strong> {director}<br>"
        movie_info_html += f"  <strong>Calificación Promedio (Ranking):</strong> {avg_rating}<br>"
        movie_info_html += f"</div>"

        if poster_url:
            movie_info_html += f"</div>"

        display(HTML(movie_info_html))
        print("-----------------------------------------")

#Lista los directores a partir de la base de datos
director_cols = [col for col in df_top500.columns if 'director/' in col]

#Dataframe de todos los directores definidso en una variable
all_directors = df_top500[director_cols].stack().dropna().tolist()

#Se define la tabla del top 10 directores con más películas en el top
director_counts = pd.Series(all_directors).value_counts().reset_index()
director_counts.columns = ['Director', 'Cantidad de Películas']
display(director_counts.head(10))

#Importan bibliotecas de datos para la creación del gráfico
import matplotlib.pyplot as plt
import seaborn as sns

#Crea gráfico de barras según cuál director tiene más películas en el top
fig = plt.figure(figsize=(12, 6))
sns.barplot(x='Cantidad de Películas', y='Director', data=director_counts.head(10), palette='viridis')
plt.title('Top 10 Directores con Más Películas en el Top 500')
plt.xlabel('Número de Películas')
plt.ylabel('Director')
plt.tight_layout()
plt.show()

#Lista los géneros a partir de la base de datos
if 'genres_combined' not in df_top500.columns:
    genre_cols = [col for col in df_top500.columns if 'genres/' in col]
    df_top500['genres_combined'] = df_top500[genre_cols].apply(lambda row: ', '.join(row.dropna().astype(str)), axis=1)

#Dataframe de todos los directores definidso en una variable
all_genres = df_top500['genres_combined'].str.split(', ').explode().str.strip().tolist()
all_genres = [genre for genre in all_genres if genre]

#Se define la tabla del top 10 directores con más películas en el top
genre_counts = pd.Series(all_genres).value_counts().reset_index()
genre_counts.columns = ['Género', 'Cantidad de Películas']
display(genre_counts.head(10))

#Importan bibliotecas de datos para la creación del gráfico
import matplotlib.pyplot as plt
import seaborn as sns

#Crea gráfico de barras según cuál director tiene más películas en el top
fig = plt.figure(figsize=(12, 6))
sns.barplot(x='Cantidad de Películas', y='Género', data=genre_counts.head(10), palette='magma')
plt.title('Top 10 Géneros Más Comunes en el Top 500')
plt.xlabel('Número de Películas')
plt.ylabel('Género')
plt.tight_layout()
plt.show()

#Poner las variantes
year_counts = df_top500['year'].value_counts().sort_index()
year_counts_df = year_counts.reset_index()
year_counts_df.columns = ['Año', 'Cantidad de Películas']

#Crear el gráfico interactivo
fig = px.line(
    year_counts_df,
    x='Año',
    y='Cantidad de Películas',
    title='Cantidad de Películas del Top 500 por Año de Estreno',
    markers=True,
    labels={'Año': 'Año de Estreno', 'Cantidad de Películas': 'Cantidad de Películas'},
    hover_name='Año',
    hover_data={'Cantidad de Películas': True}
)

fig.update_xaxes(tickangle=45)
fig.update_layout(xaxis_title='Año de Estreno', yaxis_title='Cantidad de Películas')
fig.show()

import pandas as pd
import numpy as np
import re

def cargar_y_limpiar_datos(df_source):
    """
    Adapta el DataFrame df_top500 para el sistema de recomendación,
    renombrando columnas y añadiendo placeholders para datos faltantes.
    """
    df = df_source.copy()

    # Renombrar columnas para que coincidan con la estructura esperada por las funciones de quiz/filtro
    df = df.rename(columns={
        'title': 'título',
        'year': 'año',
        'country': 'país o región',
        'averageRating': 'rating de Letterboxd'
    })

    # Renombrar columnas de directores
    director_cols_map = {f'director/{i}': f'director{i}' for i in range(3) if f'director/{i}' in df.columns}
    df = df.rename(columns=director_cols_map)

    # Renombrar columnas de géneros
    genre_cols_map = {f'genres/{i}': f'género{i}' for i in range(8) if f'genres/{i}' in df.columns}
    df = df.rename(columns=genre_cols_map)

    # Añadir columnas faltantes con valores por defecto
    if 'sinopsis' not in df.columns:
        df['sinopsis'] = '' # Sinopsis no está disponible en df_top500
    if 'duración (minutos)' not in df.columns:
        df['duración (minutos)'] = 120 # Valor por defecto, ya que la duración no está en df_top500
    if 'idioma' not in df.columns:
        df['idioma'] = 'inglés' # Valor por defecto, ya que el idioma no está en df_top500

    # Limpieza básica de strings y normalización de textos
    columnas_str = ['título', 'sinopsis', 'idioma', 'país o región'] + list(director_cols_map.values())
    for col in columnas_str:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip()

    # Normalizar columnas de géneros
    for i in range(8):
        col_gen = f'género{i}'
        if col_gen in df.columns:
            df[col_gen] = df[col_gen].astype(str).str.strip().str.capitalize()

    return df

def ejecutar_quiz():
    """
    Despliega el cuestionario interactivo mediante la consola de entrada.
    """
    print("=" * 60)
    print(" BIENVENIDO AL QUIZ INTERACTIVO DE RECOMENDACIÓN DE PELÍCULAS")
    print("=" * 60)
    print("Por favor, responde a las siguientes preguntas indicando el número o texto según corresponda:\n")

    # 1. Género
    print("1. ¿Qué género te gustaría ver hoy?")
    print("Opciones: Drama, Comedia, Acción, Thriller, Terror, Romance, Ciencia ficción, Animación, Documental, Fantasía, Crimen, Aventura, Musical, Guerra, Western, Ninguno")
    gen_pref = input("Tu respuesta: ").strip().capitalize()

    # 2. Duración
    print("\n2. ¿Qué duración prefieres?")
    print("1: Menos de 90 minutos\n2: 90–120 minutos\n3: 120–150 minutos\n4: Más de 150 minutos\n5: Me da igual")
    dur_opt = input("Tu respuesta (número): ").strip()

    # 3. Época
    print("\n3. ¿De qué época prefieres la película?")
    print("1: Antes de 1970\n2: 1970–1989\n3: 1990–2009\n4: 2010+\n5: No importa")
    ep_opt = input("Tu respuesta (número): ").strip()

    # 4. Rating
    print("\n4. ¿Qué calificación mínima en Letterboxd buscas?")
    print("1: 3.5+\n2: 4.0+\n3: 4.3+\n4: Top rated (4.5+)\n5: Me da igual")
    rat_opt = input("Tu respuesta (número): ").strip()

    # 5. Región
    print("\n5. ¿De qué región te gustaría ver una película?")
    print("Opciones: USA/Canadá, Europa, Asia, Latinoamérica, África, Oceanía, Cualquiera")
    region_opt = input("Tu respuesta: ").strip().lower()

    # 6. Idioma
    print("\n6. ¿Qué prefieres respecto al idioma?")
    print("1: Español\n2: Español/Inglés\n3: Cualquier idioma\n4: Descubrir otros (No inglés/español)")
    id_opt = input("Tu respuesta (número): ").strip()

    # 7. Experiencia emocional
    print("\n7. ¿Qué tipo de experiencia buscas?")
    print("Opciones: Emocionarme, Reflexionar, Suspenso, Reír, Sorprenderme, Indiferente")
    exp_opt = input("Tu respuesta: ").strip().lower()

    # 8. Géneros a evitar
    print("\n8. ¿Quieres evitar algún género? (Indica géneros separados por comas o escribe 'ninguno')")
    evitar_opt = input("Tu respuesta: ").strip().lower()

    # 9. Director
    print("\n9. ¿Hay algún director que te guste especialmente? (Opcional, presiona Enter para saltar)")
    dir_opt = input("Tu respuesta: ").strip().lower()

    # 10. Cantidad de recomendaciones
    print("\n10. ¿Cuántas recomendaciones deseas?")
    print("Opciones: 1, 3 o 5")
    n_recom = input("Tu respuesta: ").strip()
    try:
        n_recom = int(n_recom)
        if n_recom not in [1, 3, 5]:
            n_recom = 3
    except ValueError:
        n_recom = 3

    respuestas = {
        'genero': gen_pref,
        'duracion': dur_opt,
        'epoca': ep_opt,
        'rating': rat_opt,
        'region': region_opt,
        'idioma': id_opt,
        'experiencia': exp_opt,
        'evitar': evitar_opt,
        'director': dir_opt,
        'cantidad': n_recom
    }
    return respuestas

def filtrar_y_puntuar(df, respuestas):
    """
    Aplica filtros duros según selección y calcula un sistema de scoring adaptativo.
    """
    df_filtrado = df.copy()

    # ---- 1. FILTRADO DURO DE GÉNEROS A EVITAR ----
    if respuestas['evitar'] != 'ninguno' and respuestas['evitar'] != '':
        generos_evitar = [g.strip().capitalize() for g in respuestas['evitar'].split(',')]
        for g_evitar in generos_evitar:
            for i in range(8):
                # Asegurarse de que la columna exista antes de intentar filtrar
                if f'género{i}' in df_filtrado.columns:
                    df_filtrado = df_filtrado[df_filtrado[f'género{i}'] != g_evitar]

    # ---- 2. ASIGNACIÓN DE SCORING INTELIGENTE ----
    df_filtrado['score'] = 0.0

    # Coincidencia de Género Preferido (Peso Muy Alto: +3 puntos)
    if respuestas['genero'] != 'Ninguno' and respuestas['genero'] != '':
        gen_mask = pd.Series(False, index=df_filtrado.index)
        for i in range(8):
            if f'género{i}' in df_filtrado.columns:
                gen_mask = gen_mask | (df_filtrado[f'género{i}'] == respuestas['genero'])
        df_filtrado.loc[gen_mask, 'score'] += 3.0

    # Coincidencia de Experiencia Emocional inferida de sinopsis (Peso Alto: +2 puntos)
    dic_palabras_clave = {
        'emocionarme': ['llorar', 'amor', 'drama', 'emoción', 'conmovedor', 'familia', 'triste', 'vida'],
        'reflexionar': ['filosofía', 'mente', 'pensar', 'existencial', 'sociedad', 'realidad', 'humano', 'moral'],
        'suspenso': ['misterio', 'crimen', 'asesinato', 'tensión', 'peligro', 'secreto', 'investigación', 'terror'],
        'reír': ['comedia', 'divertido', 'humor', 'chiste', 'risa', 'sátira', 'parodia'],
        'sorprenderme': ['giro', 'inesperado', 'secreto', 'magia', 'ciencia ficción', 'fantasía', 'viaje', 'descubrir']
    }

    exp = respuestas['experiencia']
    if exp in dic_palabras_clave:
        keywords = dic_palabras_clave[exp]
        regex_pattern = '|'.join(keywords)
        # Asegurarse de que la columna 'sinopsis' exista
        if 'sinopsis' in df_filtrado.columns:
            sinopsis_match = df_filtrado['sinopsis'].str.contains(regex_pattern, case=False, na=False)
            df_filtrado.loc[sinopsis_match, 'score'] += 2.0

    # Rating de Letterboxd (Peso Alto: Máximo +2 puntos proporcionales)
    # Escala el rating de manera que las mejor valoradas sumen más al score final
    if 'rating de Letterboxd' in df_filtrado.columns:
        df_filtrado['score'] += (df_filtrado['rating de Letterboxd'].fillna(0) / 5.0) * 2.0

    # ---- 3. APLICACIÓN DE FILTROS ADAPTATIVOS / FLEXIBLES ----

    # Filtro de Duración
    dur = respuestas['duracion']
    if 'duración (minutos)' in df_filtrado.columns:
        if dur == '1': # Menos de 90
            df_filtrado.loc[df_filtrado['duración (minutos)'] < 90, 'score'] += 1.0
        elif dur == '2': # 90-120
            df_filtrado.loc[(df_filtrado['duración (minutos)'] >= 90) & (df_filtrado['duración (minutos)'] <= 120), 'score'] += 1.0
        elif dur == '3': # 120-150
            df_filtrado.loc[(df_filtrado['duración (minutos)'] > 120) & (df_filtrado['duración (minutos)'] <= 150), 'score'] += 1.0
        elif dur == '4': # Más de 150
            df_filtrado.loc[df_filtrado['duración (minutos)'] > 150, 'score'] += 1.0

    # Filtro de Época
    ep = respuestas['epoca']
    if 'año' in df_filtrado.columns:
        if ep == '1': # Antes de 1970
            df_filtrado.loc[df_filtrado['año'] < 1970, 'score'] += 1.0
        elif ep == '2': # 1970-1989
            df_filtrado.loc[(df_filtrado['año'] >= 1970) & (df_filtrado['año'] <= 1989), 'score'] += 1.0
        elif ep == '3': # 1990-2009
            df_filtrado.loc[(df_filtrado['año'] >= 1990) & (df_filtrado['año'] <= 2009), 'score'] += 1.0
        elif ep == '4': # 2010+
            df_filtrado.loc[df_filtrado['año'] >= 2010, 'score'] += 1.0

    # Filtro estricto / flexible de Rating Mínimo solicitado
    rat = respuestas['rating']
    if 'rating de Letterboxd' in df_filtrado.columns:
        if rat == '1': df_filtrado = df_filtrado[df_filtrado['rating de Letterboxd'] >= 3.5]
        elif rat == '2': df_filtrado = df_filtrado[df_filtrado['rating de Letterboxd'] >= 4.0]
        elif rat == '3': df_filtrado = df_filtrado[df_filtrado['rating de Letterboxd'] >= 4.3]
        elif rat == '4': df_filtrado = df_filtrado[df_filtrado['rating de Letterboxd'] >= 4.5]

    # Región
    reg = respuestas['region']
    if reg != 'cualquiera' and reg != '':
        mapa_regiones = {
            'usa/canadá': ['estados unidos', 'canadá', 'usa', 'united states', 'canada', 'estados unidos o canadá'],
            'europa': ['europa', 'francia', 'españa', 'reino unido', 'italia', 'alemania'],
            'asia': ['asia', 'japón', 'corea', 'china', 'india'],
            'latinoamérica': ['latinoamérica', 'argentina', 'méxico', 'brasil', 'chile', 'colombia'],
            'áfrica': ['áfrica', 'sudáfrica', 'egipto', 'nigeria'],
            'oceanía': ['oceanía', 'australia', 'nueva zelanda']
        }
        if reg in mapa_regiones and 'país o región' in df_filtrado.columns:
            reg_mask = df_filtrado['país o región'].str.lower().isin(mapa_regiones[reg])
            df_filtrado.loc[reg_mask, 'score'] += 1.0

    # Idioma
    idioma_opt = respuestas['idioma']
    if 'idioma' in df_filtrado.columns:
        if idioma_opt == '1': # Solo español
            df_filtrado = df_filtrado[df_filtrado['idioma'].str.lower() == 'español']
        elif idioma_opt == '2': # Español o inglés
            df_filtrado = df_filtrado[df_filtrado['idioma'].str.lower().isin(['español', 'inglés', 'english'])]
        elif idioma_opt == '4': # Descubrir otros
            df_filtrado = df_filtrado[~df_filtrado['idioma'].str.lower().isin(['español', 'inglés', 'english'])]

    # Director Favorito (Suma de bonus de +1.5)
    if respuestas['director'] != '':
        dir_mask = pd.Series(False, index=df_filtrado.index)
        for i in range(3):
            col_dir = f'director{i}'
            if col_dir in df_filtrado.columns:
                dir_mask = dir_mask | (df_filtrado[col_dir].str.lower() == respuestas['director'])
        df_filtrado.loc[dir_mask, 'score'] += 1.5

    # Ordenar por score de afinidad y romper empates usando el rating de Letterboxd de forma descendente
    if 'rating de Letterboxd' in df_filtrado.columns:
        df_filtrado = df_filtrado.sort_values(by=['score', 'rating de Letterboxd'], ascending=[False, False])
    else:
        df_filtrado = df_filtrado.sort_values(by='score', ascending=False)


    return df_filtrado

def mostrar_recomendaciones(df_resultados, respuestas):
    """
    Imprime el output en el formato estricto solicitado.
    """
    from IPython.display import HTML, display # Ensure these are imported here too if not globally

    n_mostrar = min(len(df_resultados), respuestas['cantidad'])

    if n_mostrar == 0:
        print("\n==================================")
        print("No se encontraron películas que coincidan exactamente con tus criterios de filtrado.")
        print("Prueba ampliando los rangos de selección o reduciendo las restricciones.")
        print("==================================")
        return

    print(f"\n Basado en tus respuestas, estas son tus {n_mostrar} mejores recomendaciones cinematográficas:\n")

    for idx in range(n_mostrar):
        peli = df_resultados.iloc[idx]

        # Recuperar géneros válidos omitiendo nulos/vacíos
        generos = []
        for i in range(8):
            gen_col = f'género{i}'
            if gen_col in peli.index:
                gen = peli[gen_col]
                if pd.notna(gen) and str(gen).strip() != '' and str(gen).lower() != 'nan':
                    generos.append(str(gen))
        generos_str = ", ".join(generos)

        # Recuperar directores válidos
        directores = []
        for i in range(3):
            col_dir = f'director{i}'
            if col_dir in peli.index and pd.notna(peli[col_dir]) and str(peli[col_dir]).strip() != '' and str(peli[col_dir]).lower() != 'nan':
                directores.append(str(peli[col_dir]))
        directores_str = ", ".join(directores)

        # Generar argumento dinámico de recomendación
        motivos = []
        if respuestas['genero'] != 'Ninguno' and respuestas['genero'] in generos:
            motivos.append(f"coincide perfectamente con tu deseo de ver un film de {respuestas['genero']}")
        if respuestas['experiencia'] != 'indiferente':
            motivos.append(f"su trama está especialmente alineada a tu búsqueda de {respuestas['experiencia']}")
        if 'rating de Letterboxd' in peli.index and float(peli['rating de Letterboxd']) >= 4.0:
            motivos.append(f"cuenta con un excelente respaldo crítico de {peli['rating de Letterboxd']} en la comunidad cinéfila")

        por_que = "Esta obra maestra te la sugiero porque " + " y ".join(motivos[:2]) + "." if motivos else "Es una de las obras con mayor afinidad y calidad dentro de tus filtros elegidos."

        # Retrieve poster URL
        poster_url = peli["posterUrl"] if "posterUrl" in peli.index and pd.notna(peli["posterUrl"]) else ""

        # Output in structured HTML format
        movie_info_html = ""
        if poster_url:
            movie_info_html += f"<div style='display:flex; align-items:center; margin-bottom: 20px;'>"
            movie_info_html += f"<img src='{poster_url}' style='width:100px; height:auto; margin-right:15px;'>"
            movie_info_html += f"<div>"
        else:
            movie_info_html += f"<div>"

        movie_info_html += f"  <strong>Título:</strong> {peli['título']}<br>"
        movie_info_html += f"  <strong>Año:</strong> {int(peli['año'])}<br>"
        movie_info_html += f"  <strong>Director:</strong> {directores_str}<br>"
        movie_info_html += f"  <strong>Calificación Promedio (Ranking):</strong> {peli['rating de Letterboxd']}<br>"
        movie_info_html += f"  <strong>Duración:</strong> {int(peli['duración (minutos)'])} minutos<br>"
        movie_info_html += f"  <strong>País:</strong> {peli['país o región']}<br>"
        movie_info_html += f"  <strong>Géneros:</strong> {generos_str}<br>"
        movie_info_html += f"  <strong>Por qué te lo recomiendo:</strong> {por_que}<br>"
        movie_info_html += f"</div>"

        if poster_url:
            movie_info_html += f"</div>"

        display(HTML(movie_info_html))
        print("-----------------------------------------")
    print("==================================")

# ---- EJECUCIÓN PRINCIPAL DEL NOTEBOOK ----
# Cargar df_top500 para asegurar su disponibilidad
df_top500 = pd.read_csv("/content/top500.csv")

# Pasar df_top500 directamente a la función de carga y limpieza
df_peliculas = cargar_y_limpiar_datos(df_top500)

print("Unique genres in the dataset after cleaning:")
all_cleaned_genres = set()
for i in range(8):
    col_gen = f'género{i}'
    if col_gen in df_peliculas.columns:
        all_cleaned_genres.update(df_peliculas[col_gen].dropna().unique())

# Remove empty strings or 'nan' if they appear
all_cleaned_genres = {g for g in all_cleaned_genres if g and g.lower() != 'nan'}

print(sorted(list(all_cleaned_genres)))

respuestas_usuario = ejecutar_quiz()
resultados = filtrar_y_puntuar(df_peliculas, respuestas_usuario)
mostrar_recomendaciones(resultados, respuestas_usuario)